name: Build
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'
      - '.github/workflows/publish.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'
      - '.github/workflows/publish.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: ['3.8', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update setuptools
        run: python -m pip install -U pip setuptools

      - name: Install
        run: pip install .[tests] --verbose

      - name: Run tests
        run: pytest test --color=yes -v

      - name: Set up Clang
        if: ${{ runner.os != 'macOS' }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Detailed build with clang++
        if: ${{ runner.os != 'macOS' }}
        env:
          CFLAGS: ${{ runner.os == 'Windows' && '/WX' || '-Werror' }}
          CC: clang
        run: pip install .[tests] --verbose
